import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { readPageFiles } from "./page-files.mjs";

const root = new URL("../", import.meta.url);
export const OUTPUT = fileURLToPath(new URL("worker/dist/worker.mjs", root));
const BANNER =
  "// Generated by worker/build.mjs from worker/src/ and page/. Edit those and rebuild.";

// Node reads the page from disk through #page-files; the Worker has no disk, so the build embeds it.
const embedPageFiles = {
  name: "embed-page-files",
  setup(bundler) {
    bundler.onResolve({ filter: /^#page-files$/ }, () => ({
      path: "page-files",
      namespace: "page-files",
    }));
    bundler.onLoad({ filter: /.*/, namespace: "page-files" }, () => ({
      contents: `export default ${JSON.stringify(readPageFiles())};`,
      loader: "js",
    }));
  },
};

export async function buildWorker() {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("worker/src/index.js", root))],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    banner: { js: BANNER },
    plugins: [embedPageFiles],
    write: false,
  });
  return result.outputFiles[0].text;
}

function readCurrentBuild() {
  try {
    return readFileSync(OUTPUT, "utf8");
  } catch {
    return "";
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const built = await buildWorker();
  if (process.argv.includes("--check")) {
    if (readCurrentBuild() !== built) {
      console.error("worker/dist/worker.mjs is out of date. Run: npm run build");
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, built);
    console.log(`Wrote ${OUTPUT} (${built.length} bytes)`);
  }
}
