import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { readPageFiles } from "./page-files.mjs";
import { readVersion } from "./release.mjs";

const root = new URL("../", import.meta.url);
const OUTPUT = fileURLToPath(new URL("worker/dist/worker.mjs", root));
const BANNER =
  "// Generated by worker/build.mjs from worker/src/ and page/. Edit those and rebuild.";

const runGit = (args) => execFileSync("git", args, { cwd: fileURLToPath(root), encoding: "utf8" });

/**
 * Names the commit being built and its version, for the page's settings. Only deploys go live, so
 * the build time is the deploy time.
 * @returns {{ version: string | null, commit: string, builtAt: string } | null}
 */
export function readRelease(git = runGit, now = new Date()) {
  let commit;
  try {
    commit = git(["log", "-1", "--format=%h"]).trim();
  } catch {
    return null;
  }
  return { version: readVersion(git), commit, builtAt: now.toISOString() };
}

function listBundledFiles(release) {
  const files = readPageFiles();
  if (!release) return files;
  return {
    ...files,
    "version.json": { contentType: "application/json", text: JSON.stringify(release) },
  };
}

// Node reads the page from disk through #page-files; the Worker has no disk, so the build embeds it.
const embedPageFiles = (release) => ({
  name: "embed-page-files",
  setup(bundler) {
    bundler.onResolve({ filter: /^#page-files$/ }, () => ({
      path: "page-files",
      namespace: "page-files",
    }));
    bundler.onLoad({ filter: /.*/, namespace: "page-files" }, () => ({
      contents: `export default ${JSON.stringify(listBundledFiles(release))};`,
      loader: "js",
    }));
  },
});

export async function buildWorker({ release = readRelease() } = {}) {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("worker/src/index.js", root))],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    banner: { js: BANNER },
    plugins: [embedPageFiles(release)],
    write: false,
  });
  return result.outputFiles[0].text;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const built = await buildWorker();
  mkdirSync(path.dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, built);
  console.log(`Wrote ${OUTPUT} (${built.length} bytes)`);
}
