import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = new URL("../", import.meta.url);
export const OUTPUT = fileURLToPath(new URL("worker/dist/worker.mjs", root));
const BANNER =
  "// Generated by worker/build.mjs from worker/src/ and page/js/snapshot.js. Edit those and rebuild.";

export async function buildWorker() {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("worker/src/index.js", root))],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    banner: { js: BANNER },
    write: false,
  });
  return result.outputFiles[0].text;
}

function readCurrentBuild() {
  try {
    return readFileSync(OUTPUT, "utf8");
  } catch {
    return "";
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const built = await buildWorker();
  if (process.argv.includes("--check")) {
    if (readCurrentBuild() !== built) {
      console.error("worker/dist/worker.mjs is out of date. Run: npm run build");
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, built);
    console.log(`Wrote ${OUTPUT} (${built.length} bytes)`);
  }
}
